export const gladiatorStyleInit = {
  MURMILLO: {
    init_strength: 5,
    init_dexterity: 3,
    init_agility: 1,
    init_weapon: 'basic_shord',
    init_shield: 'basic_big_shield',
    init_head_armor: 'basic_helmet',
    init_arms_armor: 'basic_arm_armor',
    init_chest_armor: 'none',
    init_legs_armor: 'none',
  },
  THRAEX: {
    init_strength: 2,
    init_dexterity: 4,
    init_agility: 3,
    init_weapon: 'basic_sword',
    init_shield: 'basic_small_shield',
    init_head_armor: 'basic_helmet',
    init_arms_armor: 'basic_arm_armor',
    init_chest_armor: 'none',
    init_legs_armor: 'none',
  },
  RETIARIUS: {
    init_strength: 1,
    init_dexterity: 5,
    init_agility: 3,
    init_weapon: 'basic_trident',
    init_shield: 'net',
    init_head_armor: 'none',
    init_arms_armor: 'basic_arm_armor',
    init_chest_armor: 'none',
    init_legs_armor: 'none',
  },
  DIAMACHAERUS: {
    init_strength: 2,
    init_dexterity: 2,
    init_agility: 5,
    init_weapon: 'basic_sword',
    init_shield: 'none',
    init_head_armor: 'none',
    init_arms_armor: 'basic_arm_armor',
    init_chest_armor: 'none',
    init_legs_armor: 'none',
  },
};
